# Generated by Django 5.2.7 on 2025-10-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedido_total_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
