# Generated by Django 5.2.7 on 2025-10-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuario_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='avatar',
        ),
    ]
