# Generated by Django 5.2.7 on 2025-10-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_usuario_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='producto',
        ),
        migrations.AddField(
            model_name='oferta',
            name='precio_oferta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='oferta',
            name='productos',
            field=models.ManyToManyField(related_name='ofertas', to='core.producto'),
        ),
    ]
