# Generated by Django 5.2.7 on 2025-11-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_oferta_producto_oferta_precio_oferta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alerta_stock_enviada',
            field=models.BooleanField(default=False, help_text='Indica si ya se envió la notificación de stock agotado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario'),
        ),
    ]
