# Generated by Django 5.2.7 on 2025-11-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_detallepedido_options_alter_oferta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alerta_stock_bajo_enviada',
            field=models.BooleanField(
                default=False, 
                help_text='Indica si ya se envió la notificación de stock bajo (≤10 unidades)'
            ),
        ),
    ]