# Generated by Django 5.2.7 on 2025-11-23
# PASO 1: Crear el modelo ProductoOferta primero

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_producto_alerta_stock_bajo_enviada'),
    ]

    operations = [
        # Crear la tabla intermedia
        migrations.CreateModel(
            name='ProductoOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de este producto en la oferta')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.oferta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
            options={
                'verbose_name': 'Producto en Oferta',
                'verbose_name_plural': 'Productos en Ofertas',
                'ordering': ['oferta', 'producto'],
                'unique_together': {('oferta', 'producto')},
            },
        ),
    ]