# Generated by Django 5.2.7 on 2025-11-23
# PASO 2: Migrar datos existentes de ofertas

from django.db import migrations


def migrar_productos_a_tabla_intermedia(apps, schema_editor):
    """
    Migra los productos existentes en ofertas a la nueva tabla intermedia
    con cantidad = 1 por defecto
    """
    Oferta = apps.get_model('core', 'Oferta')
    ProductoOferta = apps.get_model('core', 'ProductoOferta')
    
    for oferta in Oferta.objects.all():
        for producto in oferta.productos.all():
            # Crear la relación en la nueva tabla con cantidad=1
            ProductoOferta.objects.get_or_create(
                oferta=oferta,
                producto=producto,
                defaults={'cantidad': 1}
            )
    
    print(f"✅ Migrados productos de ofertas existentes")


def revertir_migracion(apps, schema_editor):
    """
    Función para revertir la migración si es necesario
    """
    ProductoOferta = apps.get_model('core', 'ProductoOferta')
    ProductoOferta.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_productooferta'),
    ]

    operations = [
        migrations.RunPython(
            migrar_productos_a_tabla_intermedia,
            revertir_migracion
        ),
    ]