# Generated by Django 5.2.7 on 2025-11-23
# PASO 3: Eliminar la relación ManyToMany antigua

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_migrar_datos_productos'),
    ]

    operations = [
        # Eliminar la relación ManyToMany antigua
        migrations.RemoveField(
            model_name='oferta',
            name='productos',
        ),
    ]