# Generated by Django 5.2.7 on 2025-11-23
# PASO 4: Crear la nueva relación ManyToMany con through

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_old_m2m_productos'),
    ]

    operations = [
        # Agregar la nueva relación ManyToMany con through
        migrations.AddField(
            model_name='oferta',
            name='productos',
            field=models.ManyToManyField(
                related_name='ofertas',
                through='core.ProductoOferta',
                to='core.producto'
            ),
        ),
    ]