# Generated by Django 5.2.7 on 2025-11-24 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_new_m2m_with_through'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='alerta_stock_enviada',
            field=models.BooleanField(default=False, help_text='Indica si ya se envió la notificación de stock agotado (=0)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('administrador', 'Administrador'), ('administrador_general', 'Administrador General')], default='cliente', max_length=25),
        ),
        migrations.AddField(
            model_name='oferta',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal a la que pertenece esta oferta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal a la que pertenece este producto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal asignada (solo para administradores)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.sucursal'),
        ),
    ]
