# Generated by Django 5.2.7 on 2025-12-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sucursal_alter_producto_alerta_stock_enviada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.TextField(blank=True, help_text='Dirección de entrega del pedido (copia del domicilio del usuario)', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='domicilio',
            field=models.TextField(blank=True, help_text='Dirección de entrega del cliente', null=True),
        ),
    ]
