# Generated by Django 5.2.7 on 2025-12-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pedido_direccion_entrega_usuario_domicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('domicilio', 'Entrega a Domicilio'), ('recoger', 'Recoger en Sucursal')], default='domicilio', help_text='Tipo de entrega del pedido', max_length=20),
        ),
    ]
