# Generated by Django 5.2.7 on 2025-12-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el pedido fue entregado o cancelado', null=True),
        ),
    ]
